baseURL: "https://narumi.dev/"
languageCode: zh-tw
defaultcontentlanguage: zh-tw
title: なるみ
description: "Hi, I'm Narumi, a machine learning engineer."
theme: PaperMod
enableRobotsTXT: true

menu:
  main:
    - identifier: posts
      name: Posts
      url: "/"
      weight: 1
    - identifier: archives
      name: Archive
      url: "/archives/"
      weight: 2
    - identifier: search
      name: Search
      url: "/search/"
      weight: 3
    - identifier: tags
      name: Tags
      url: "/tags/"
      weight: 4
    - identifier: about
      name: About
      url: "/about/"
      weight: 5

taxonomies:
  category: categories
  tag: tags

# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
outputs:
  home:
    - html
    - rss
    - json

params:
  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/
  ShowShareButtons: "true"
  ShowReadingTime: "true"
  ShowPostNavLinks: "true"
  ShowCodeCopyButtons: "true"

  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#adding-custom-favicons
  assets:
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple-touch-icon.png

  # https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/#home-info-mode
  homeInfoParams:
    Title: Welcome to Narumi's blog
    Content: "Hi, I'm Narumi, a machine learning engineer."
    socialIcons:
      - name: github
        url: "https://github.com/narumiruna"

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: "0.5"
