baseURL = "https://narumi.dev/"
languageCode = "zh-tw"
defaultcontentlanguage = "zh-tw"
title = "なるみ"
description = "Hi, I'm Narumi, a machine learning engineer."
theme = "PaperMod"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 2

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5

[taxonomies]
category = "categories"
tag = "tags"

# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
[outputs]
home = ["html", "rss", "json"]

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-variables/
[params]
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-faq/#adding-custom-favicons
[params.assets]
favicon = "favicon.ico"
favicon16x16 = "favicon-16x16.png"
favicon32x32 = "favicon-32x32.png"
apple_touch_icon = "apple-touch-icon.png"

[params.homeInfoParams]
Title = "Welcome to Narumi's blog"
Content = "Hi, I'm Narumi, a machine learning engineer."

[[params.socialIcons]]
name = "github"
url = "https://github.com/narumiruna"

[sitemap]
changefreq = "always"
filename = "sitemap.xml"
priority = 0.5
