baseURL = 'http://narumi.dev/'
languageCode = 'zh-tw'
defaultcontentlanguage = 'zh'
title = 'なるみ'
theme = "PaperMod"
math = true

[languages]
  [languages.en]
    languagecode = 'en-us'
    
  [languages.zh]
    languageCode = 'zh-tw'

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archive"
url = "/archives/"
weight = 2

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 5

[taxonomies]
category = "categories"
tag = "tags"

# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#search-page
[outputs]
home = ['html', 'rss', 'json']

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.assets]
favicon = 'favicon.ico'
favicon16x16 = 'favicon-16x16.png'
favicon32x32 = 'favicon-32x32.png'
apple_touch_icon = 'apple-touch-icon.png'

[params.homeInfoParams]
Title = ""
Content = ""

[[params.socialIcons]]
name = "github"
url = "https://github.com/narumiruna"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5
