baseURL = 'http://blog.narumi.dev/'
languageCode = 'zh-tw'
title = 'なるみ'
theme = "PaperMod"
math = true

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[taxonomies]
category = "categories"
tag = "tags"
